-- 코드를 입력하세요
SELECT AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, SUM(BOOK.PRICE*BOOK_SALES.SALES) AS TOTAL_SALES
FROM BOOK_SALES 
JOIN BOOK ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE BOOK_SALES.SALES_DATE LIKE '2022-01%' 
GROUP BY BOOK.CATEGORY, AUTHOR_ID
ORDER BY BOOK.AUTHOR_ID, BOOK.CATEGORY DESC